### PR TITLE
Fix analyze and reanalyze button 

### PR DESCRIPTION
**Pull request by nicooxxx**
## Background

This PR fixes two regressions in the Report Analyst analysis workflow and adds integration tests for both affected buttons.

The **Analyze Selected Questions** button raised a `KeyError` because the selected questions were filtered using `edited_df["Select"] is True` instead of the pandas boolean mask.

The **Reanalyze** button failed because `pre_retrieved_chunks` was not forwarded through `ReportAnalyzer.process_document()`, resulting in an unexpected keyword argument error. This regression was introduced in #83.

In addition, neither workflow was covered by integration tests.

## Goals

- Restore the Analyze button functionality.
- Restore the Reanalyze button functionality.
- Add integration tests for both analysis workflows.
- Ensure the tests run without requiring an OpenAI API key or a locally stored PDF.

## Acceptance Criteria

- The Analyze button correctly processes the selected questions without raising a `KeyError`.
- The Reanalyze button forwards `pre_retrieved_chunks` correctly.
- Integration tests cover both Analyze and Reanalyze workflows.
- The tests mock analysis calls so no external OpenAI requests are made.
- The tests generate a valid PDF at runtime instead of relying on a local test document.

### CODE REVIEW

**Review by mounacheikho-cmd — APPROVED** [review]
The buttons work now and acceptance criteria is met. Thank you!
